name: clean_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn=1.3.2
  - jupyter
  - notebook
  - ipykernel
  - opencv
  - pip:
      - tensorflow==2.15.0
      - imbalanced-learn==0.11.0
      - mlflow
      - tqdm
      - joblib
      - pyyaml